# Uncomment the next line to define a global platform for your project
 #platform :ios, '9.0'
	#github "https://github.com/Yalantis/Koloda"
source 'https://github.com/CocoaPods/Specs.git'
target 'AIAroundYou' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AIAroundYou
	
	pod 'JSQMessagesViewController'
	pod 'Koloda'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
	
  target 'AIAroundYouTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AIAroundYouUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
